-- Audit trail for task changes. Append-only: rows are only ever INSERTed, never UPDATEd or DELETEd.
-- One row per changed field (a single edit touching N fields produces N rows, grouped by change_set_id).

CREATE TABLE task_activity (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Soft references (no FK constraints): the trail must OUTLIVE the task/user it records,
    -- so deleting a task or user must not cascade-delete or null out its history. The numeric
    -- ids are kept as-is, and the snapshot columns below keep each row human-readable even
    -- after the referenced row is gone.
    task_id       BIGINT       NOT NULL,
    task_title    VARCHAR(255) NOT NULL,                 -- self-describing snapshot of the task at write time
    user_id       BIGINT,                                -- the actor; nullable to allow non-user/system actions
    username      VARCHAR(255),                          -- self-describing snapshot of the actor

    action        VARCHAR(255) NOT NULL,                 -- CREATE | UPDATE | DELETE
    field_changed VARCHAR(255),                          -- which field changed (NULL for whole-entity CREATE/DELETE)
    old_value     TEXT,                                  -- stringified prior value (NULL on CREATE)
    new_value     TEXT,                                  -- stringified new value (NULL on DELETE)

    change_set_id VARCHAR(36),                           -- groups the rows produced by one atomic edit
    created_at    TIMESTAMP    NOT NULL
);

-- Reads are always "activity for task X, newest first" and are paginated, so index that access path.
CREATE INDEX idx_task_activity_task ON task_activity (task_id, created_at);

-- Immutability note: append-only is enforced operationally in production by granting the
-- application's DB user INSERT/SELECT (but NOT UPDATE/DELETE) on this table. The application
-- itself never exposes any path that modifies or removes an existing audit row.
